/**
 * Per-page anchor builders for the sidebar.
 *
 * The DS sidebar reveals each page's top-level sections as anchor
 * sub-items when that page is active. These helpers produce the
 * `children` arrays that DsShell wires into each top-level NavItem.
 *
 * Strategy:
 *   - Where a registry already exposes the section list (colours,
 *     typography, motion, anomalies), derive from it so changes
 *     propagate automatically.
 *   - Where the page itself defines the sections in JSX (tokens,
 *     logo, iconography, map), hardcode the titles here. Keep them
 *     in sync with the page when adding/renaming sections.
 *
 * Anchor `href` is always the page path + `#<slug>`. The slug must
 * match the id auto-generated by the Section component for that
 * title (see sectionSlug() in components/design-system/section.tsx).
 * That's why we use the same slug logic here.
 */

import {
  rawColorGroups,
  semanticColorGroups,
} from "./colors"
import { typeGroups } from "./typography"
import { motionCategoryInfo } from "./motion"
import {
  anomalies,
  categoryInfo as anomalyCategoryInfo,
  type AnomalyCategory,
} from "./anomalies"

// One sub-item of a sidebar nav. Mirrors the NavItem children shape
// used by DsShell.
type Anchor = { href: string; label: string }

// Same slug logic as Section's sectionSlug(). Duplicated here to
// avoid pulling a "use client" component into a registry file.
function slug(title: string): string {
  return title
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
}

function anchor(basePath: string, title: string): Anchor {
  return { href: `${basePath}#${slug(title)}`, label: title }
}

// --- Colour ---------------------------------------------------------
// Both semantic + raw groups in their on-page order. ~13 sub-items —
// the longest in the sidebar but still readable at sidebar width.
export function colorAnchors(): Anchor[] {
  const path = "/design-system/colors"
  return [
    ...semanticColorGroups.map((g) => anchor(path, g.title)),
    ...rawColorGroups.map((g) => anchor(path, g.title)),
  ]
}

// --- Layout tokens --------------------------------------------------
// Sections are hardcoded in the page (Spacing, Border radius,
// Breakpoints, Root font size). Keep this list in sync if any of
// those headings change.
export function tokenAnchors(): Anchor[] {
  const path = "/design-system/tokens"
  return [
    anchor(path, "Spacing"),
    anchor(path, "Border radius"),
    anchor(path, "Breakpoints"),
    anchor(path, "Root font size"),
  ]
}

// --- Typography ----------------------------------------------------
// Fonts is a fixed top section; the rest come from typeGroups.
export function typographyAnchors(): Anchor[] {
  const path = "/design-system/typography"
  return [
    anchor(path, "Fonts"),
    ...typeGroups.map((g) => anchor(path, g.title)),
  ]
}

// --- Motion --------------------------------------------------------
// Use the same category order as the Motion page (loading → modal →
// state → map → feedback) so sidebar order matches page order.
export function motionAnchors(): Anchor[] {
  const path = "/design-system/motion"
  const order = ["loading", "modal", "state", "map", "feedback"] as const
  return order.map((c) => anchor(path, motionCategoryInfo[c].name))
}

// --- Logo ----------------------------------------------------------
// Hardcoded in the page.
export function logoAnchors(): Anchor[] {
  const path = "/design-system/logo"
  return [
    anchor(path, "Full logo"),
    anchor(path, "Logomark"),
    anchor(path, "Mask-tint technique"),
  ]
}

// --- Iconography ---------------------------------------------------
// Hardcoded in the page.
export function iconographyAnchors(): Anchor[] {
  const path = "/design-system/iconography"
  return [
    anchor(path, "Favicons"),
    anchor(path, "Loading spinner"),
    anchor(path, "Hero artwork"),
    anchor(path, "Icon libraries"),
  ]
}

// --- Map -----------------------------------------------------------
// Hardcoded in the page.
export function mapAnchors(): Anchor[] {
  const path = "/design-system/map"
  return [
    anchor(path, "Mapbox style"),
    anchor(path, "Station markers"),
    anchor(path, "Polylines"),
    anchor(path, "Labels"),
    anchor(path, "Hover state"),
  ]
}

// --- Anomalies -----------------------------------------------------
// Only show categories that currently have at least one entry —
// otherwise the sub-item is dead weight.
export function anomalyAnchors(): Anchor[] {
  const path = "/design-system/anomalies"
  const present = new Set(anomalies.map((a) => a.category))
  const order: AnomalyCategory[] = [
    "color",
    "typography",
    "structure",
    "iconography",
    "motion",
    "external",
  ]
  return order
    .filter((c) => present.has(c))
    .map((c) => anchor(path, anomalyCategoryInfo[c].name))
}
